### PR TITLE
Avoid collision between branch and tag name

### LINKED ISSUE #451: tag detection is confused when a branch is named like a tag
Hi,

I was releasing dune 3.6.1. One branch was called 3.6.1 (that's the PR where I prepared the changelog for 3.6.1).
`dune-released` correctly inferred from the changelog that the version was 3.6.1; however it refused to create an annotated tag:

```
dune-release tag
[-] Extracting tag from first entry in CHANGES.md
[-] Using tag "3.6.1"
[-] Nothing to be done: tag already exists.
```

After switching to a different branch and removing the 3.6.1 branch this worked.
I suppose that the function that looks for existing tags is looking at all refs, not just annotated tags.

### PR DESCRIPTION
**Pull request by 3Rafal**
This should resolve #451

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
Hi! Thanks for your contribution! Can you add a changelog entry and Mercurial support?

**Review by Leonidas-from-XIV — APPROVED** [review]
Looks good to me, recommend to merge when CI is green.

**Comment by pitag-ha** [comment]
Nice, thanks, @3Rafal! Looks good to me as well.

**Comment by 3Rafal** [comment]
@Leonidas-from-XIV , @pitag-ha 
Thanks for quick response. 🙂 CI has finished successfully, so I guess we can merge this PR now.

**Comment by Leonidas-from-XIV** [comment]
Yup, let's goooo! Thanks again.

**Pull request merged**
