### PR TITLE
Upgrade to opam 2.1

### PR DESCRIPTION
**Pull request by kit-ty-kate**
opam 2.1 hasn't been released yes so I'll keep that as a draft for now.
I've been using this branch for a few months now and haven't noticed any issues yet.

### CODE REVIEW

**Comment by NathanReb** [comment]
This looks good but we'll need https://github.com/ocaml/opam-file-format/pull/32 to preserve the current behaviour. I'll give that a try on top of that PR to see if it works well and then we can merge once this is released!

**Comment by emillon** [comment]
I'll have a look at that mdx failure.

**Comment by NathanReb** [comment]
This is likely to just be a change in how opam prints the file, in which case I think we can just promote the change, the order of the fields doesn't really matter here!

**Comment by emillon** [comment]
No, there's something going on with how the ellipsis is interpreted. Trying to reduce now!

**Comment by NathanReb** [comment]
Ah yeah my bad! To be honest these cram tests are rather fragile and don't bring in much value. We should simplify the meaningful ones and get rid of the others.

Let me know if you find away around that ellipsis failure otherwise I'll rewrite that tests!

**Comment by emillon** [comment]
After some debugging, it's a bug in mdx where EOL-ellipses can not be used after whole-line ellipses. I'll file that against mdx for completeness but the best solution is indeed to migrate to postprocessing. We don't have `jq` for opam files, so here's a solution using sed: (I can't push to your branch but this works):

```diff
-    $ cat _build/whatever.0.1.0/opam
+    $ cat _build/whatever.0.1.0/opam |\
+    > sed -e 's/\(sha...\)=[0-9a-f]*/\1/' \
+    >     -e 's/\(x-commit-hash:\) "[0-9a-f]*"/\1/'
```

**Comment by emillon** [comment]
I think it's better to omit the ellipsis (`...`) in the output to make sure plain string matching is used.

**Comment by kit-ty-kate** [comment]
Fair enough. Done!

**Comment by emillon** [comment]
See https://github.com/realworldocaml/mdx/issues/329

**Comment by kit-ty-kate** [comment]
All green and ready to go

**Comment by kit-ty-kate** [comment]
cc @emillon @NathanReb

**Pull request merged**
