### PR TITLE
Better report GitHub API errors

### LINKED ISSUE #289: Github API errors should be better reported
At the moment we only report the `message` field from the API response but this field alone is not very helpful.
For example, see the following Github API response:
```json
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "PullRequest",
      "code": "custom",
      "message": "A pull request already exists for kit-ty-kate:release-opam-0install-0.3."
    }
  ],
  "documentation_url": "https://docs.github.com/rest/reference/pulls#create-a-pull-request"
}
```

Printing the message alone is not giving much feedback on why the request failed, we should probably just print the whole JSON.

### PR DESCRIPTION
**Pull request by gpetiot**
Fix #289

### CODE REVIEW

**Comment by gpetiot** [comment]
Can we merge this one?

**Review by pitag-ha — COMMENTED** [review]
Thanks, I like the PR, it's very well-readable! 

Just one general doubt: in the issue (#290), @NathanReb proposed to log the whole JSON. Here you are logging all `message` values in the JSON, but leaving out the other values. I'm doubting if if might be good to also log (at least some of) the other values for 2 reasons:
-  If I understand the [github documentation](https://developer.github.com/v3/#client-errors) correctly, the objects in `errors` only contain a `message`, if the error is a custom error. If not, the important information seems to be in the error code name (key `code`).
- I think some other values might also be pretty helpful. E.g., the one of `documentation_url` might be interesting to the user.

Why did you decide to only log the `message` values?

**Comment by gpetiot** [comment]
I changed the data representation, from what I get in the github api documentation this kind of handled error should be checked with the deeper messages anyway (for the kind of errors we handle in dune-release for now, that is only when a PR already exists)
I also added the `code` and `documentation_url` fields in the output.

**Review by pitag-ha — APPROVED** [review]
Thanks! To me it looks good.

**Pull request merged**
